version: '3.9'

services:
  web:
    build: ./budget_planner
    command: gunicorn budget_planner.wsgi:application --bind 0.0.0.0:8000 -t 1200 -w 3
    volumes:
      - static:/home/budget_planner/budget_planner/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  nginx:
    build: ./nginx
    volumes:
      - static:/home/budget_planner/budget_planner/staticfiles
    ports:
      - 1337:80
    depends_on:
      web:
        condition: service_started

  redis:
    image: redis:alpine
    expose:
      - 6379

volumes:
  static:
    driver: local
